/**
 * src/constants/LiveData.ts
 * 静的なマスターデータの保持
 */
import type { LiveEvent, LiveDetail } from '@/types/live'; // 👈 LiveDetail を追加

/**
 * LIVE_DATA 定数
 * LiveEvent の定義に合わせ、prefecture と isChecked を含めています。
 */
export const LIVE_DATA: LiveEvent[] = [
  { id: "20260129001", artist: "HYDE", tourName: "HYDE Orchestra Tour 2026 JEKYLL", date: "2026/01/29", venue: "東京ガーデンシアター", prefecture: "東京都", isChecked: false },
  { id: "20260502001", artist: "B'z", tourName: "B'z LIVE-GYM 2026 FYOP+", date: "2026/05/02", venue: "沖縄アリーナ", prefecture: "沖縄県", isChecked: false },
  { id: "20260503001", artist: "B'z", tourName: "B'z LIVE-GYM 2026 FYOP+", date: "2026/05/03", venue: "沖縄アリーナ", prefecture: "沖縄県", isChecked: false },
  { id: "20251220001", artist: "B'z", tourName: "B'z LIVE-GYM 2025 FYOP", date: "2025/12/20", venue: "京セラドーム大阪", prefecture: "大阪府", isChecked: false },
  { id: "20251221001", artist: "B'z", tourName: "B'z LIVE-GYM 2025 FYOP", date: "2025/12/21", venue: "京セラドーム大阪", prefecture: "大阪府", isChecked: false },
  { id: "20240413001", artist: "L'Arc~en~Ciel", tourName: "ARENA TOUR 2024 UNDERGROUND", date: "2024/04/13", venue: "横浜アリーナ", prefecture: "神奈川県", isChecked: false },
  { id: "20240414001", artist: "L'Arc~en~Ciel", tourName: "ARENA TOUR 2024 UNDERGROUND", date: "2025/04/14", venue: "横浜アリーナ", prefecture: "神奈川県", isChecked: false },
];

/**
 * LIVE_DETAIL_DATA 定数（新設）
 * Live一覧タブ画面で表示するための詳細モックデータです。
 * 将来的にはAWSのデータベースに移行されるデータとなります。
 */
export const LIVE_DETAIL_DATA: LiveDetail[] = [
  {
    id: '20260129001',
    artist: "HYDE",
    tourName: 'HYDE Orchestra Tour 2026 JEKYLL',
    date: '2026/01/29',
    venue: '東京ガーデンシアター',
    prefecture: '東京都',
    isChecked: false,
    year: 2026,
    setlist: [
      { songOrder: 1, songTitle: 'DIE HAPPILY' },
      { songOrder: 2, songTitle: 'SSS (Sending Secret Signals)' },
      { songOrder: 3, songTitle: 'MAISIE' },
      { songOrder: 4, songTitle: 'SO DREAMY' },
      { songOrder: 5, songTitle: 'HONEY' },
      { songOrder: 6, songTitle: 'GLAMOROUS SKY' },
      { songOrder: 7, songTitle: 'NOSTALGIC' },
      { songOrder: 8, songTitle: 'TATTOO' },
      { songOrder: 9, songTitle: 'FINAL PIECE' },
      { songOrder: 10, songTitle: 'DEFEAT' },
      { songOrder: 11, songTitle: 'FADING OUT' },
      { songOrder: 12, songTitle: 'SMILING' },
      { songOrder: 13, songTitle: 'evergreen' },
      { songOrder: 14, songTitle: 'THE ABYSS' },
      { songOrder: 15, songTitle: 'BREAKING DAWN' },
      { songOrder: 16, songTitle: '夢幻' },
      { songOrder: 17, songTitle: 'LAST SONG' },
      { songOrder: 18, songTitle: 'Red Swan' },
    ]
  },
  {
    id: '20260502001',
    artist: "B'z",
    tourName: "B'z LIVE-GYM 2026 FYOP+",
    date: '2026/05/02',
    venue: '沖縄アリーナ',
    prefecture: '沖縄県',
    isChecked: false,
    year: 2026,
    setlist: [
      { songOrder: 1, songTitle: 'FAITH?' },
      { songOrder: 2, songTitle: '濁流BOY' },
      { songOrder: 3, songTitle: 'ZERO' },
      { songOrder: 4, songTitle: 'おでかけしましょ' },
      { songOrder: 5, songTitle: 'love me, I love you' },
      { songOrder: 6, songTitle: '今夜月の見える丘に' },
      { songOrder: 7, songTitle: 'ペインキラー' },
      { songOrder: 8, songTitle: '片翼の風景' },
      { songOrder: 9, songTitle: '鞭' },
      { songOrder: 10, songTitle: '今では…今なら…今も…' },
      { songOrder: 11, songTitle: '#1090 ～Million Dreams～' },
      { songOrder: 12, songTitle: 'ハピネス' },
      { songOrder: 13, songTitle: 'イルミネーション' },
      { songOrder: 14, songTitle: 'FMP' },
      { songOrder: 15, songTitle: '有頂天' },
      { songOrder: 16, songTitle: 'Heaven Knows' },
      { songOrder: 17, songTitle: 'Liar! Liar!' },
      { songOrder: 18, songTitle: 'ultra soul' },
      { songOrder: 19, songTitle: 'その先へ' },
      { songOrder: 20, songTitle: 'ミエナイチカラ ～INVISIBLE ONE～' },
    ]
  },
  {
    id: '20260503001',
    artist: "B'z",
    tourName: "B'z LIVE-GYM 2026 FYOP+",
    date: '2026/05/03',
    venue: '沖縄アリーナ',
    prefecture: '沖縄県',
    isChecked: false,
    year: 2026,
    setlist: [
      { songOrder: 1, songTitle: 'FAITH?' },
      { songOrder: 2, songTitle: '濁流BOY' },
      { songOrder: 3, songTitle: "IT'S SHOWTIME!!"},
      { songOrder: 4, songTitle: 'HI' },
      { songOrder: 5, songTitle: 'ねがい' },
      { songOrder: 6, songTitle: 'イチブトゼンブ' },
      { songOrder: 7, songTitle: 'ペインキラー' },
      { songOrder: 8, songTitle: 'INTO THE BLUE' },
      { songOrder: 9, songTitle: 'The ⅢRD Eye' },
      { songOrder: 10, songTitle: 'shower' },
      { songOrder: 11, songTitle: '#1090 ～Million Dreams～' },
      { songOrder: 12, songTitle: "Don't Leave Me" },
      { songOrder: 13, songTitle: 'イルミネーション' },
      { songOrder: 14, songTitle: 'FMP' },
      { songOrder: 15, songTitle: '有頂天' },
      { songOrder: 16, songTitle: 'Heaven Knows' },
      { songOrder: 17, songTitle: 'さまよえる蒼い弾丸' },
      { songOrder: 18, songTitle: 'ultra soul' },
      { songOrder: 19, songTitle: 'その先へ' },
      { songOrder: 20, songTitle: 'ミエナイチカラ ～INVISIBLE ONE～' },
    ]
  },
  {
    id: '20251221001',
    artist: "B'z",
    tourName: "B'z LIVE-GYM 2025 FYOP",
    date: '2025/12/21',
    venue: '京セラドーム大阪',
    prefecture: '大阪府',
    isChecked: false,
    year: 2025,
    setlist: [
      { songOrder: 1, songTitle: 'FMP' },
      { songOrder: 2, songTitle: '兵、走る' },
      { songOrder: 3, songTitle: "声明"},
      { songOrder: 4, songTitle: 'MY LONELY TOWN' },
      { songOrder: 5, songTitle: 'DIVE' },
      { songOrder: 6, songTitle: '恐るるなかれ灰は灰に' },
      { songOrder: 7, songTitle: 'INTO THE BLUE' },
      { songOrder: 8, songTitle: 'The ⅢRD Eye' },
      { songOrder: 9, songTitle: 'shower' },
      { songOrder: 10, songTitle: '消えない虹' },
      { songOrder: 11, songTitle: "Tiger's Eye" },
      { songOrder: 12, songTitle: "LOVE PHANTOM" },
      { songOrder: 13, songTitle: 'ultra soul' },
      { songOrder: 14, songTitle: '鞭' },
      { songOrder: 15, songTitle: 'Still Alive' },
      { songOrder: 16, songTitle: 'juice' },
      { songOrder: 17, songTitle: 'Brotherhood' },
      { songOrder: 18, songTitle: 'いつかのメリークリスマス' },
      { songOrder: 19, songTitle: 'イルミネーション' },
      { songOrder: 20, songTitle: '愛のバクダン' },
    ]
  },
  {
    id: '20251220001',
    artist: "B'z",
    tourName: "B'z LIVE-GYM 2025 FYOP",
    date: '2025/12/20',
    venue: '京セラドーム大阪',
    prefecture: '大阪府',
    isChecked: false,
    year: 2025,
    setlist: [
      { songOrder: 1, songTitle: 'FMP' },
      { songOrder: 2, songTitle: '兵、走る' },
      { songOrder: 3, songTitle: "声明"},
      { songOrder: 4, songTitle: 'MY LONELY TOWN' },
      { songOrder: 5, songTitle: 'DIVE' },
      { songOrder: 6, songTitle: '恐るるなかれ灰は灰に' },
      { songOrder: 7, songTitle: 'INTO THE BLUE' },
      { songOrder: 8, songTitle: 'The ⅢRD Eye' },
      { songOrder: 9, songTitle: 'Homebound' },
      { songOrder: 10, songTitle: 'キレイな愛じゃなくても' },
      { songOrder: 11, songTitle: "Tiger's Eye" },
      { songOrder: 12, songTitle: "LOVE PHANTOM" },
      { songOrder: 13, songTitle: 'ultra soul' },
      { songOrder: 14, songTitle: '鞭' },
      { songOrder: 15, songTitle: 'Still Alive' },
      { songOrder: 16, songTitle: 'juice' },
      { songOrder: 17, songTitle: 'Brotherhood' },
      { songOrder: 18, songTitle: 'いつかのメリークリスマス' },
      { songOrder: 19, songTitle: 'イルミネーション' },
      { songOrder: 20, songTitle: 'イチブトゼンブ' },
    ]
  },
  {
    id: '20240414001',
    artist: "L'Arc~en~Ciel",
    tourName: "ARENA TOUR 2024 UNDERGROUND",
    date: '2024/04/14',
    venue: '横浜アリーナ',
    prefecture: '神奈川県',
    isChecked: false,
    year: 2024,
    setlist: [
      { songOrder: 1, songTitle: 'THE BLACK ROSE' },
      { songOrder: 2, songTitle: 'EXISTENCE' },
      { songOrder: 3, songTitle: "THE NEPENTHES"},
      { songOrder: 4, songTitle: '砂時計' },
      { songOrder: 5, songTitle: 'a silent letter' },
      { songOrder: 6, songTitle: 'Ophelia' },
      { songOrder: 7, songTitle: 'Taste of love' },
      { songOrder: 8, songTitle: 'Voice' },
      { songOrder: 9, songTitle: 'Vivid Colors' },
      { songOrder: 10, songTitle: 'flower' },
      { songOrder: 11, songTitle: "It's the end" },
      { songOrder: 12, songTitle: "Cureless" },
      { songOrder: 13, songTitle: 'Blame' },
      { songOrder: 14, songTitle: '叙情詩' },
      { songOrder: 15, songTitle: 'GOOD LUCK MY WAY' },
      { songOrder: 16, songTitle: 'Killing Me' },
      { songOrder: 17, songTitle: 'NEXUS 4' },
      { songOrder: 18, songTitle: 'Bye Bye' },
      { songOrder: 19, songTitle: 'ミライ' },
      { songOrder: 20, songTitle: 'Link' },
      { songOrder: 21, songTitle: 'MY HEART DRAWS A DREAM' },
    ]
  },
  {
    id: '20240413001',
    artist: "L'Arc~en~Ciel",
    tourName: "ARENA TOUR 2024 UNDERGROUND",
    date: '2024/04/13',
    venue: '横浜アリーナ',
    prefecture: '神奈川県',
    isChecked: false,
    year: 2024,
    setlist: [
      { songOrder: 1, songTitle: 'All Dead' },
      { songOrder: 2, songTitle: 'EXISTENCE' },
      { songOrder: 3, songTitle: "THE NEPENTHES"},
      { songOrder: 4, songTitle: '砂時計' },
      { songOrder: 5, songTitle: 'a silent letter' },
      { songOrder: 6, songTitle: 'Ophelia' },
      { songOrder: 7, songTitle: 'Taste of love' },
      { songOrder: 8, songTitle: 'Voice' },
      { songOrder: 9, songTitle: 'Vivid Colors' },
      { songOrder: 10, songTitle: 'flower' },
      { songOrder: 11, songTitle: "It's the end" },
      { songOrder: 12, songTitle: "shade of season" },
      { songOrder: 13, songTitle: 'Blame' },
      { songOrder: 14, songTitle: '叙情詩' },
      { songOrder: 15, songTitle: 'GOOD LUCK MY WAY' },
      { songOrder: 16, songTitle: 'Killing Me' },
      { songOrder: 17, songTitle: '自由への招待' },
      { songOrder: 18, songTitle: 'Bye Bye' },
      { songOrder: 19, songTitle: 'ミライ' },
      { songOrder: 20, songTitle: 'Link' },
      { songOrder: 21, songTitle: 'MY HEART DRAWS A DREAM' },
    ]
  },
  // 必要に応じて 2022年、2023年のデータも追加してください
];